version: 2
jobs:
  build:
    working_directory: ~/openmct
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      # - run:
      #     name: check version
      #     command: npm --version
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: gulp lint
      - run:
          name: all done
          command: echo "WOO!"